[design]
vcode = "tests/demo/vcode.f"
define = ["RTL_SIM"]   # preprocessor defines passed to pyslang for AST parsing

[rtltree]
show_instance_name = true   # show "cpu (u_cpu)" instead of just "cpu"
show_file = true             # show "[rtl/cpu.sv]" after module name

[formatter]
indent_size = 4
keyword_case = "lower"          # "lower" | "upper" | "preserve"
max_line_length = 120
compact_indexing_and_selections = true
blank_lines_between_items = 1
default_indent_level_inside_module_block = 0
tab_align = true
# align_punctuation = false

[formatter.statement]
align = true                # align = and <= operators in consecutive assignments
lhs_min_width = 5           # minimum width of the LHS column before the operator
wrap_end_else_clauses = false
wrap_spaces = 4

[formatter.port_declaration]
align = true
section1_min_width = 10
section2_min_width = 33
section3_min_width = 20
section4_min_width = 30
section5_min_width = 30

[formatter.var_declaration]
align = true
section1_min_width = 22
section2_min_width = 30
section3_min_width = 30
section4_min_width = 10

[formatter.instance]
align = true
port_indent_level = 1           # indent levels for port lines relative to instantiation
port_spacing_before_paren = 10  # spaces between port name and (
port_spacing_inside_paren = 10  # spaces between signal and )

[autofunc]
use_named_arguments = true
